name: build

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            arch: x86_64
          - platform: linux/arm64
            arch: aarch64

    steps:
    - uses: actions/checkout@v3
    - name: Download package
      env:
        PKG_NAME: glibc-bin-2.37-0-${{ matrix.arch }}.tar.gz
      run: |
        wget -q https://github.com/Rory-Z/docker-glibc-builder/releases/download/2.37-1/$PKG_NAME
        sed -i "48s/.*/$(sha512sum $PKG_NAME)/" APKBUILD
    - name: Change APKBUILD
      if: matrix.arch == 'aarch64'
      run: |
        sed -i 's/x86_64/aarch64/g' APKBUILD
        sed -i 's/x86-64/aarch64/g' APKBUILD
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build
      run: |
        openssl genrsa -out ssh.rsa 3072
        openssl rsa -in ssh.rsa -pubout -out ssh.rsa.pub
        docker run --platform ${{ matrix.platform }} \
          -v $(pwd)/ssh.rsa:/home/builder/ssh.rsa \
          -v $(pwd)/ssh.rsa.pub:/home/builder/ssh.rsa.pub \
          -v $(pwd):/home/builder/package \
          -v $(pwd)/output:/packages \
          sgerrand/alpine-abuild:latest
    - name: Rename package
      run: |
        cd output/builder/${{ matrix.arch }}
        while read -r pkg; do sudo mv $pkg $(echo "$pkg" | sed "s/glibc-\(.*\).apk/glibc-\1-${{ matrix.arch }}.apk/") ;done < <(find . -name "*.apk")
    - uses: actions/upload-artifact@v2
      with:
        name: pkg
        path: output/builder/${{ matrix.arch }}/glibc-*.apk

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: pkg
    - name: Get file list
      id: get_file_list
      run: |
        echo "files<<EOF" >> $GITHUB_OUTPUT
        echo "$(find $(pwd) -name '*.apk')" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        token: ${{ github.token }}
        name: ${{ github.repository }} ${{ github.ref_name }} Released
        body: ${{ github.repository }} ${{ github.ref_name }} has been released
        fail_on_unmatched_files: true
        files: |
          ${{ steps.get_file_list.outputs.files }}
    - uses: geekyeggo/delete-artifact@v2
      with:
        name: pkg

